// Author: Kyle Angeles
// File-Name: TermsConditions.jsx
// Description: This view just hosts the privacy policy of this
// TODO: Tomorrow 
function TermsConditions () {


    const sections = [
        {
            TermsConditions: "By accessing or using [Risk Diabetes Predictor ] (the \"Service\"), you agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Service. We reserve the right to update or modify these Terms at any time without prior notice, and your continued use of the Service after any changes constitutes acceptance of the revised Terms.\n\n[Risk Diabetes Predictor] provides a lifestyle and wellness questionnaire that generates informational predictions related to diabetes risk factors based on information you voluntarily provide, including but not limited to diet, exercise habits, sleep patterns, family history, and reported symptoms. The Service is intended for general informational and educational purposes only.\n\nThe Service is not a substitute for professional medical advice, diagnosis, or treatment. The predictions, assessments, or insights generated by [Diabetes Risk Predictor] are not medical diagnoses and should not be relied upon as such. Always seek the advice of a qualified physician or other healthcare provider with any questions you may have regarding a medical condition. Never disregard professional medical advice or delay seeking it because of something you have read or received through this Service. If you believe you may be experiencing a medical emergency, call your doctor or emergency services immediately.\n\nTo use certain features of the Service, you may be required to create an account. You are responsible for maintaining the confidentiality of your account credentials and for all activity that occurs under your account. You agree to provide accurate, current, and complete information during registration and to update such information as necessary. We reserve the right to suspend or terminate accounts that provide false or misleading information.\n\nYou agree to use the Service only for lawful purposes and in accordance with these Terms. You agree not to misuse the Service, interfere with its normal operation, attempt to gain unauthorized access to any portion of the Service, or use the Service to transmit any harmful, misleading, or unlawful content.\n\nAny information you submit through the questionnaire, including health-related information, is collected and processed in accordance with our Privacy Policy. By using the Service, you consent to the collection, use, and storage of your information as described therein.\n\nAll content, features, and functionality of the Service, including but not limited to text, graphics, logos, and software, are the exclusive property of [Kyle Angeles] or its licensors and are protected by applicable intellectual property laws. You may not reproduce, distribute, modify, or create derivative works of any part of the Service without our prior written consent.\n\nThe Service is provided on an \"as is\" and \"as available\" basis without warranties of any kind, either express or implied, including but not limited to warranties of merchantability, fitness for a particular purpose, or non-infringement. We do not warrant that the Service will be uninterrupted, error-free, or that any predictions or results generated will be accurate or reliable.\n\nTo the fullest extent permitted by law, [Kyle Angeles] shall not be liable for any indirect, incidental, special, consequential, or punitive damages, or any loss of data, use, goodwill, or other intangible losses, resulting from your access to or use of, or inability to access or use, the Service, including any reliance placed on predictions or information generated by the Service.\n\nWe reserve the right to suspend or terminate your access to the Service at any time, without notice, for conduct that we believe violates these Terms or is otherwise harmful to other users of the Service, us, or third parties, or for any other reason at our sole discretion.\n\nThese Terms shall be governed by and construed in accordance with the laws of [Jurisdiction], without regard to its conflict of law provisions. Any disputes arising under or in connection with these Terms shall be subject to the exclusive jurisdiction of the courts located in [Jurisdiction].\n\nIf you have any questions about these Terms and Conditions, please contact us at [contact email or method]."
        }
    ];

    return (
        <>
            <div className="text-black block mb-1">Terms and Conditions</div>
            <div className="space-y-6 w-full">
                {sections.map((section, i) => (
                    <div key={i}>
                          <p className="p-2 mt-2 w-full border border-gray-500/30 rounded outline-none text-gray-500" style={{ whiteSpace: "pre-line"}}>{section.TermsConditions}</p>
                    </div> 
                ))}
            </div>
            
            <p className="text-center text-gray-400 text-xs mt-16">
                Questions? Contact {" "}
                <a href="mailto:kyleangeles2006@gmail.com" className="underline">
                    kyleangeles2006@gmail.com
                </a>
            </p>
            
        </>
    );
}

export default TermsConditions;